# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 17a3a0ca40f6f531e38905f5543c287dedefc25b1bf7020a5796eae4daa01f3264a1112cf8dbe2089fb20cdf1c5202c76a80666624b8515eb3809b8fe8af12f7

test:
  secret_key_base: 087a5d0f6d98d7f5c9eac3a8a457f635dc1779ef579dffd50f987bd7807f303a8f21aa57d8c0c243a214d95e9d5cb1e4c81d726bf108abbc3ff9616da137010d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
